[build]
  base = "audio-store"
  publish = "audio-store/build"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "16.14.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
